### ISSUE TITLE
이름 저장 테스트

### ISSUE THREAD

**Issue by chs98412** [chs98412/fifa4myplayer#2]
### TODO
 1. [ ] 이름 입력 테스트
 2. [ ] 이름 저장 테스트
 3. [ ] 이름 중복 확인 테스트

 ### 예상 작업 시간
1h
